import type { Meta, StoryObj } from "@storybook/react-vite";
import type { ReactNode } from "react";
import { Box, ThemeProvider, Typography } from "@mui/material";
import ProgressStep, { VerticalStepperBreadcrumbs } from "./ProgressStep";
import {
  ApplicationFormContext,
  type ApplicationFormValues,
} from "../../app/ApplicationFormContext";
import { generateFormDataUpToPage } from "../../dev/utils/generateFormData";
import { createAppTheme } from "../../app/theme";
import type { PageId } from "../../types";
import {
  ApplicationSessionContext,
  type ApplicationSessionContextValue,
} from "../../app/ApplicationSessionContext";

/**
 * ProgressStep is the outer step navigator FormRoutePage wraps every gated
 * page in: a sticky vertical Stepper sidebar on desktop, or an accordion
 * Stepper (StepContent expands under the active step) on mobile — both
 * driven by the same `getActiveProgressSteps`/`getActiveProgressStepIndex`
 * config, which drops any step whose pages are all skipped for the current
 * form values (e.g. no coverage selected yet collapses Beneficiary and every
 * Health sub-step). VerticalStepperBreadcrumbs is a second, independent
 * consumer of that same config — the breadcrumb trail FormRoutePage renders
 * *inside* the page content, above PageHeader, so users can jump between
 * sibling pages within the current step (e.g. between Health sub-pages)
 * without leaving it. Both read form values from ApplicationFormContext, so
 * every story below supplies fixed demo values directly through that
 * context rather than the real sessionStorage-backed provider, keeping
 * stories isolated from each other and from the running app's saved
 * progress.
 */
const meta = {
  title: "Navigation/ProgressStep",
  parameters: { layout: "fullscreen" },
} satisfies Meta;

export default meta;

type Story = StoryObj;

function withDemoValues(
  values: ApplicationFormValues,
  children: ReactNode,
  session: Partial<ApplicationSessionContextValue> = {},
) {
  const sessionValue: ApplicationSessionContextValue = {
    reviewSubmitted: false,
    advisorApplicantFlow: false,
    markReviewSubmitted: () => {},
    setAdvisorApplicantFlow: () => {},
    resetApplicationSession: () => {},
    ...session,
  };

  return (
    <ApplicationSessionContext.Provider value={sessionValue}>
      <ApplicationFormContext.Provider
        value={{ values, setPageValues: () => {}, resetValues: () => {} }}
      >
        {children}
      </ApplicationFormContext.Provider>
    </ApplicationSessionContext.Provider>
  );
}

function DemoPageContent({ label }: { label: string }) {
  return (
    <Box sx={{ p: 3, border: "1px dashed", borderColor: "divider", borderRadius: 2 }}>
      <Typography variant="body2" color="text.secondary">
        {label}
      </Typography>
    </Box>
  );
}

export const CollapsedSteps: Story = {
  name: "Default — no coverage selected yet (steps collapsed)",
  render: () =>
    withDemoValues(
      {},
      <ProgressStep pageId={"eligibility" as PageId}>
        <DemoPageContent label="Eligibility page content" />
      </ProgressStep>,
    ),
  parameters: {
    docs: {
      description: {
        story:
          "With no coverage selected, Beneficiary and every Health-* page are skipped, so their steps (or the pages within them) disappear entirely rather than rendering as disabled — the step count itself is data-driven, not fixed at 5.",
      },
    },
  },
};

export const ExpandedWithHealthBreadcrumb: Story = {
  name: "Health coverage selected (Review step expands, breadcrumb consolidates)",
  render: () => {
    const pageId = "health-si" as PageId;
    const values = generateFormDataUpToPage(pageId);
    return withDemoValues(
      values,
      <ProgressStep pageId={pageId}>
        <Box sx={{ mb: 2 }}>
          <VerticalStepperBreadcrumbs pageId={pageId} />
        </Box>
        <DemoPageContent label="Health — Simplified Issue page content" />
      </ProgressStep>,
    );
  },
  parameters: {
    docs: {
      description: {
        story:
          "Real dummy data generated by the same generateFormDataUpToPage() helper the app's own ?autofill= debug param uses. Selecting SI-underwritten coverage unlocks the health-si page, which the Review step's config lists alongside review/health-li/health-qd/health-di/health-cir/payment. The breadcrumb above the content consolidates all Health-* pages into a single \"Health\" entry with a completed checkmark once its pages are behind the current one — this is the exact composition FormRoutePage renders (breadcrumb nested inside ProgressStep's children, above PageHeader).",
      },
    },
  },
};

export const Mobile: Story = {
  name: "Mobile layout (forceMobileLayout)",
  render: () => {
    const pageId = "health-si" as PageId;
    const values = generateFormDataUpToPage(pageId);
    const forcedMobileTheme = createAppTheme("default", {
      forceMobileLayout: true,
    });
    return (
      <ThemeProvider theme={forcedMobileTheme}>
        {withDemoValues(
          values,
          <ProgressStep pageId={pageId}>
            <Box sx={{ mb: 2 }}>
              <VerticalStepperBreadcrumbs pageId={pageId} />
            </Box>
            <DemoPageContent label="Health — Simplified Issue page content" />
          </ProgressStep>,
        )}
      </ThemeProvider>
    );
  },
  parameters: {
    docs: {
      description: {
        story:
          "Uses the same forceMobileLayout theme technique as Foundations/Breakpoints to pin the mobile branch regardless of the Storybook canvas's actual width, rather than requiring the viewport toolbar. Below md, the Stepper becomes an accordion — StepContent only renders (and only mounts children) for the active step, instead of the desktop sidebar-plus-separate-content-column layout.",
      },
    },
  },
};

export const LockedAfterReviewSubmitted: Story = {
  name: "Locked — after Review has been submitted",
  render: () => {
    const pageId = "payment" as PageId;
    const values = generateFormDataUpToPage(pageId);
    return withDemoValues(
      values,
      <ProgressStep pageId={pageId}>
        <DemoPageContent label="Payment page content" />
      </ProgressStep>,
      { reviewSubmitted: true },
    );
  },
  parameters: {
    docs: {
      description: {
        story:
          "Once review has been submitted, ApplicationSessionContext locks completed earlier steps — click one to confirm nothing navigates. This prevents editing answers behind a submitted application without adding a second confirmation dialog.",
      },
    },
  },
};

export const AdvisorApplicantHandoff: Story = {
  name: "Locked — advisor-completed steps during applicant handoff",
  render: () => {
    const pageId = "review" as PageId;
    const values = generateFormDataUpToPage(pageId);
    return withDemoValues(
      values,
      <ProgressStep pageId={pageId}>
        <DemoPageContent label="Review page content" />
      </ProgressStep>,
      { advisorApplicantFlow: true },
    );
  },
  parameters: {
    docs: {
      description: {
        story:
          'When an applicant resumes via an advisor-sent link (resume?flow=advisor), ApplicationSessionContext locks Getting Started/Coverage/Profile even though they show as completed — only Review and E-sign stay clickable. This remains independent from the "submitted" lock above.',
      },
    },
  },
};

export const BreadcrumbStandalone: Story = {
  name: "VerticalStepperBreadcrumbs (standalone)",
  render: () => {
    const pageId = "health-di" as PageId;
    const values = generateFormDataUpToPage(pageId);
    return withDemoValues(values, <VerticalStepperBreadcrumbs pageId={pageId} />);
  },
  parameters: {
    layout: "padded",
    docs: {
      description: {
        story:
          "Renders in isolation (no ProgressStep wrapper) to show just the breadcrumb trail. Returns null whenever the current step has only one page — most steps other than Review never render this at all.",
      },
    },
  },
};
