import type { CoverageDefinition } from "./types";

export const coverages: CoverageDefinition[] = [
  {
    id: "li-term",
    code: "TL",
    categoryId: "LI",
    name: "Term Life",
    definition: "Provides term life coverage for a specified period of time.",
    applicants: ["member", "spouse", "child"],
    underwritingType: "FUW",
    minAmount: 25000,
    maxAmount: 500000,
    spouseMinAmount: 10000,
    spouseMaxAmount: 250000,
    childMinAmount: 5000,
    childMaxAmount: 50000,
    options: [{ id: "amount", type: "amount", choices: [] }],
  },
  {
    id: "li-10yr",
    code: "10TL",
    categoryId: "LI",
    name: "10-Year Level Term",
    definition: "Provides level term life coverage for 10 years.",
    applicants: ["member", "spouse", "child"],
    underwritingType: "FUW",
    minAmount: 25000,
    maxAmount: 500000,
    spouseMinAmount: 10000,
    spouseMaxAmount: 250000,
    childMinAmount: 5000,
    childMaxAmount: 50000,
    options: [{ id: "amount", type: "amount", choices: [] }],
  },
  {
    id: "li-15yr",
    code: "15TL",
    categoryId: "LI",
    name: "15-Year Level Term",
    definition: "Provides level term life coverage for 15 years.",
    applicants: ["member", "spouse", "child"],
    underwritingType: "FUW",
    minAmount: 25000,
    maxAmount: 500000,
    spouseMinAmount: 10000,
    spouseMaxAmount: 250000,
    childMinAmount: 5000,
    childMaxAmount: 50000,
    options: [{ id: "amount", type: "amount", choices: [] }],
  },
  {
    id: "li-20yr",
    code: "20TL",
    categoryId: "LI",
    name: "20-Year Level Term",
    definition: "Provides level term life coverage for 20 years.",
    applicants: ["member", "spouse", "child"],
    underwritingType: "FUW",
    minAmount: 25000,
    maxAmount: 500000,
    spouseMinAmount: 10000,
    spouseMaxAmount: 250000,
    childMinAmount: 5000,
    childMaxAmount: 50000,
    options: [{ id: "amount", type: "amount", choices: [] }],
  },
  {
    id: "li-50plus",
    code: "50PLUS",
    categoryId: "LI",
    name: "50+ Life",
    definition:
      "Provides life coverage designed for eligible applicants age 50 and over.",
    applicants: ["member", "spouse"],
    underwritingType: "GI",
    minAmount: 10000,
    maxAmount: 100000,
    spouseMinAmount: 5000,
    spouseMaxAmount: 50000,
    options: [{ id: "amount", type: "amount", choices: [] }],
  },
  {
    id: "li-add",
    code: "ADD",
    categoryId: "AD",
    name: "Accidental Death and Dismemberment",
    definition:
      "Provides coverage for accidental death or certain accidental injuries.",
    applicants: ["member", "spouse", "child"],
    underwritingType: "NA",
    minAmount: 25000,
    maxAmount: 500000,
    spouseMinAmount: 10000,
    spouseMaxAmount: 250000,
    childMinAmount: 5000,
    childMaxAmount: 25000,
    options: [{ id: "amount", type: "amount", choices: [] }],
  },
  {
    id: "li-preferred",
    code: "PREF",
    categoryId: "LI",
    name: "Preferred Life",
    definition:
      "Provides life coverage with product terms specific to the preferred offering.",
    applicants: ["member", "spouse"],
    underwritingType: "FUW",
    minAmount: 50000,
    maxAmount: 1000000,
    spouseMinAmount: 25000,
    spouseMaxAmount: 500000,
    options: [{ id: "amount", type: "amount", choices: [] }],
  },
  {
    id: "li-premier-accident",
    code: "PA",
    categoryId: "AD",
    name: "Premier Accident",
    definition:
      "Provides accident coverage with benefits for covered accidental injuries.",
    minAmount: 50000,
    maxAmount: 500000,
    spouseMinAmount: 25000,
    spouseMaxAmount: 250000,
    childMinAmount: 10000,
    childMaxAmount: 100000,
    applicants: ["member", "spouse", "child"],
    underwritingType: "NA",
    options: [{ id: "amount", type: "amount", choices: [] }],
  },
  {
    id: "li-group-term",
    code: "GTL",
    categoryId: "LI",
    name: "Group Term Life",
    definition: "Provides group term life coverage for eligible applicants.",
    applicants: ["member", "spouse", "child"],
    underwritingType: "GI",
    minAmount: 10000,
    maxAmount: 300000,
    spouseMinAmount: 5000,
    spouseMaxAmount: 150000,
    childMinAmount: 2000,
    childMaxAmount: 25000,
    options: [{ id: "amount", type: "amount", choices: [] }],
  },
  {
    id: "di-ltd-plus",
    code: "LTDI+",
    categoryId: "DI",
    name: "Long-Term Disability Plus",
    definition: "Provides long-term disability income protection.",
    applicants: ["member"],
    underwritingType: "FUW",
    options: [
      { id: "amount", type: "amount", choices: [] },
      { id: "benefit-option", type: "benefit-option", choices: [] },
      { id: "waiting-period", type: "waiting-period", choices: [] },
    ],
  },
  {
    id: "di-ltd",
    code: "LTDI",
    categoryId: "DI",
    name: "Long-Term Disability",
    definition: "Provides long-term disability income protection.",
    applicants: ["member"],
    underwritingType: "FUW",
    options: [
      { id: "amount", type: "amount", choices: [] },
      { id: "benefit-option", type: "benefit-option", choices: [] },
      { id: "waiting-period", type: "waiting-period", choices: [] },
    ],
  },
  {
    id: "di-mtd",
    code: "MTD",
    categoryId: "DI",
    name: "Mid-Term Disability",
    definition:
      "Provides disability income protection for a mid-term benefit period.",
    applicants: ["member"],
    underwritingType: "FUW",
    options: [
      { id: "amount", type: "amount", choices: [] },
      { id: "benefit-option", type: "benefit-option", choices: [] },
      { id: "waiting-period", type: "waiting-period", choices: [] },
    ],
  },
  {
    id: "di-step-rated",
    code: "STDI",
    categoryId: "DI",
    name: "Step-Rated Disability",
    definition:
      "Provides disability income protection with step-rated premium structure.",
    applicants: ["member"],
    underwritingType: "FUW",
    options: [
      { id: "amount", type: "amount", choices: [] },
      { id: "benefit-option", type: "benefit-option", choices: [] },
      { id: "waiting-period", type: "waiting-period", choices: [] },
    ],
  },
  {
    id: "di-level-rated",
    code: "LTDI",
    categoryId: "DI",
    name: "Level-Rated Disability",
    definition:
      "Provides disability income protection with level premium structure.",
    applicants: ["member"],
    underwritingType: "FUW",
    options: [
      { id: "amount", type: "amount", choices: [] },
      { id: "benefit-option", type: "benefit-option", choices: [] },
      { id: "waiting-period", type: "waiting-period", choices: [] },
    ],
  },
  {
    id: "di-short-term",
    code: "STDI",
    categoryId: "DI",
    name: "Short-Term Disability",
    definition: "Provides short-term disability income protection.",
    applicants: ["member"],
    underwritingType: "GI",
    options: [
      { id: "amount", type: "amount", choices: [] },
      { id: "benefit-option", type: "benefit-option", choices: [] },
      { id: "waiting-period", type: "waiting-period", choices: [] },
    ],
  },
  {
    id: "oo-professional",
    code: "OO",
    categoryId: "OO",
    name: "Office Overhead",
    definition:
      "Helps cover eligible office overhead expenses if the insured becomes disabled.",
    applicants: ["member"],
    underwritingType: "FUW",
    options: [
      { id: "amount", type: "amount", choices: [] },
      { id: "benefit-option", type: "benefit-option", choices: [] },
      { id: "waiting-period", type: "waiting-period", choices: [] },
    ],
  },
  {
    id: "oo-office-overhead",
    code: "OO",
    categoryId: "OO",
    name: "Office Overhead",
    definition:
      "Helps cover eligible office overhead expenses if the insured becomes disabled.",
    applicants: ["member"],
    underwritingType: "FUW",
    options: [
      { id: "amount", type: "amount", choices: [] },
      { id: "benefit-option", type: "benefit-option", choices: [] },
      { id: "waiting-period", type: "waiting-period", choices: [] },
    ],
  },
  {
    id: "sh-critical-illness",
    code: "CI",
    categoryId: "SH",
    name: "Critical Illness",
    definition: "Provides a benefit for covered critical illnesses.",
    applicants: ["member", "spouse", "child"],
    underwritingType: "FUW",
    minAmount: 10000,
    maxAmount: 100000,
    spouseMinAmount: 5000,
    spouseMaxAmount: 50000,
    childMinAmount: 5000,
    childMaxAmount: 25000,
    options: [{ id: "amount", type: "amount", choices: [] }],
  },
  {
    id: "sh-hospital-money",
    code: "HI",
    categoryId: "SH",
    name: "Hospital Money",
    definition: "Provides benefits related to covered hospital stays.",
    applicants: ["member", "spouse", "child"],
    underwritingType: "FUW",
    minAmount: 500,
    maxAmount: 5000,
    spouseMinAmount: 500,
    spouseMaxAmount: 3000,
    childMinAmount: 250,
    childMaxAmount: 2000,
    options: [{ id: "amount", type: "amount", choices: [] }],
  },
  {
    id: "sh-hospital-income",
    code: "HI",
    categoryId: "SH",
    name: "Hospital Income",
    definition: "Provides benefits related to covered hospital confinement.",
    applicants: ["member", "spouse", "child"],
    underwritingType: "FUW",
    minAmount: 500,
    maxAmount: 5000,
    spouseMinAmount: 500,
    spouseMaxAmount: 3000,
    childMinAmount: 250,
    childMaxAmount: 2000,
    options: [{ id: "amount", type: "amount", choices: [] }],
  },
];
