import type { FieldOption } from "./types";

const waepaFederalAgencyLabels = [
  "Administration for Children and Families",
  "Administrative Conference of the United States",
  "Administrative Review Board",
  "Agricultural Marketing Service",
  "Agricultural Research Service",
  "American Battle Monuments Commission",
  "Animal and Plant Health Inspection Service",
  "Architect of the Capitol",
  "Arctic Institute of North America",
  "Armed Forces Retirement Home",
  "Benefits Review Board",
  "Bonneville Power Administration",
  "Broadcasting Board of Governors",
  "Bureau of Alcohol, Tobacco, Firearms and Explosives",
  "Bureau of Economic Analysis",
  "Bureau of Engraving & Printing",
  "Bureau of Fiscal Service",
  "Bureau of Indian Affairs",
  "Bureau of Industry and Security",
  "Bureau of International Labor Affairs",
  "Bureau of Labor Statistics",
  "Bureau of Land Management",
  "Bureau of Ocean Energy Management",
  "Bureau of Reclamation",
  "Bureau of Safety and Environment Enforcement",
  "Centers for Disease Control and Prevention",
  "Centers for Medicare & Medicaid Services",
  "Central Intelligence Agency",
  "Citizenship and Immigration Services",
  "Civil Aeronautics Board",
  "Commission of Fine Arts",
  "Commission on Civil Rights",
  "Commodity Futures Trading Commission",
  "Congressional Budget Office",
  "Congress Staff & Comm",
  "Consumer Financial Protection Bureau",
  "Consumer Product Safety Commission",
  "Corporation for National and Community Service",
  "Court Services and Offender Supervision Agency",
  "Customs and Border Protection",
  "Cybersecurity and Infrastructure Security Agency",
  "Defense Advanced Research Projects Agency",
  "Defense Commissary Agency",
  "Defense Contract Audit Agency",
  "Defense Contract Management Agency",
  "Defense Finance and Accounting Service",
  "Defense Information Systems Agency",
  "Defense Intelligence Agency",
  "Defense Legal Services Agency",
  "Defense Logistics Agency",
  "Defense Security Cooperation Agency",
  "Defense Security Service",
  "Defense Threat Reduction Agency",
  "Department of Agriculture",
  "Department of Commerce",
  "Department of Defense",
  "Department of Education",
  "Department of Energy",
  "Department of Health and Human Services",
  "Department of Homeland Security",
  "Department of Housing and Urban Development",
  "Department of Interior",
  "Department of Justice",
  "Department of Labor",
  "Department of State",
  "Department of Transportation",
  "Department of Treasury",
  "Department of Veterans Affairs",
  "Drug Enforcement Administration",
  "Economic and Statistics Administration",
  "Economic Development Administration",
  "Employee Benefits Security Administration",
  "Employee Compensation Appeals Board",
  "Employment & Training Administration",
  "Environmental Protection Agency",
  "Equal Employment Opportunity Commission",
  "Executive Office of the President",
  "Executive Office of Immigration Review",
  "Export-Import Bank of the U.S.",
  "Farm Credit Administation",
  "Farm Service Agency",
  "Federal Accounting Standards Advisory Board",
  "Federal Acquisition Commission",
  "Federal Aviation Administration",
  "Federal Bureau of Investigation",
  "Federal Bureau of Prisons",
  "Federal Communications Commission",
  "Federal Deposit Insurance Corporation",
  "Federal Election Commission",
  "Federal Emergency Management Agency",
  "Federal Energy Regulatory Commission",
  "Federal Highway Administration",
  "Federal Home Loan Bank Board",
  "Federal Housing Finance Agency",
  "Federal Housing Finance Board",
  "Federal Labor Relations Authority",
  "Federal Maritime Commission",
  "Federal Mediation and Conciliation Service",
  "Federal Railroad Administration",
  "Federal Reserve System",
  "Federal Retirement Thrift Investment Board",
  "Federal Trade Commission",
  "Food and Drug Administration",
  "Food and Nutrition Service",
  "Food Safety and Inspection Service",
  "Foreign Agricultural Service",
  "Foreign Claims Settlement Commission",
  "Forest Service",
  "General Services Administration",
  "Government Accountability Office",
  "Government Employees Health Association",
  "Government of Guam",
  "Government Publishing Office",
  "Grain Inspection Packers and Stockyards Administration",
  "Health Resources & Services Administration",
  "House of Representatives",
  "Immigration and Customs Enforcement",
  "Indian Health Service",
  "Inter-American Foundation",
  "Internal Revenue Service",
  "International Boundary and Water Commission",
  "International Commerce Commission",
  "International Trade Administration",
  "International Trade Commission",
  "John F. Kennedy Center for the Performing Arts",
  "Legal Services Corporation",
  "Library of Congress",
  "Merit Systems Protection Board",
  "Millennium Challenge Corporation",
  "Mine Safety & Health Administration",
  "Miscellaneous",
  "Missile Defense Agency",
  "National Academy of Sciences",
  "National Aeronautics Space Administration",
  "National Archives Records Administration",
  "National Background Investigations Bureau",
  "National Capital Planning Commission",
  "National Credit Union Administration",
  "National Endowment for the Arts",
  "National Endowment for the Humanities",
  "National Finance Center",
  "National Gallery of Art",
  "National Geospatial Intelligence Agency",
  "National Heart, Lung, and Blood Institute",
  "National Highway Traffic Safety Administration",
  "National Institute of Food and Agriculture",
  "National Institute of Standards and Technology",
  "National Institutes of Health",
  "National Labor Relations Board",
  "National Mediation Board",
  "National Nuclear Security Administration",
  "National Oceanic Atmospheric Administration",
  "National Park Service",
  "National Reconnaissance Office",
  "National Science Foundation",
  "National Security Agency",
  "National Security Division",
  "National Technical Information Service",
  "National Telecommunications and Information Administration",
  "National Transportation Safety Board",
  "Natural Resources Conservation Service",
  "Northern Boarder Regional Commission",
  "Nuclear Regulatory Commission",
  "Occupational Safety & Health Administration",
  "Occupational Safety and Health Review Comm",
  "Office of Management and Budget",
  "Office of Personnel Management",
  "Office of Science",
  "Office of the Comptroller of the Currency",
  "Office of the Director of National Intelligence",
  "Office of Thrift Supervision",
  "Overseas Private Investment Corporation",
  "Peace Corps",
  "Pension Benefit Guaranty Corporation",
  "Postal Regulatory Commission",
  "Railroad Retirement Board",
  "Resolution Trust Corporation",
  "Securities and Exchange Commission",
  "Selective Service System",
  "Senate Staff & Comm",
  "Small Business Administration",
  "Smithsonian Institution",
  "Social Security Administration",
  "Substance Abuse and Mental Health Services Administration",
  "Supreme Court of the United States",
  "Tennessee Valley Authority",
  "Transportation Security Administration",
  "Trust Territories",
  "U.S. Agency for International Development",
  "U.S. Air Force",
  "U.S. Arms Control and Disarmament Agency",
  "U.S. Army",
  "U.S. Army Corps of Engineers",
  "U.S. Attorneys Office",
  "U.S. Capitol Police",
  "U.S. Census Bureau",
  "U.S. Coast Guard",
  "U.S. Courts",
  "U.S. Fish and Wildlife Service",
  "U.S. Geological Survey",
  "U.S. Holocaust Memorial Museum",
  "U.S. Information Agency",
  "U.S. Marine Corps",
  "U.S. Marshals Service",
  "U.S. Mint",
  "U.S. Navy",
  "U.S. Patent and Trademark Office",
  "U.S. Postal Inspection Service",
  "U.S. Postal Service",
  "U.S. Postal Service Office of the Inspector General",
  "U.S. Secret Service",
  "U.S. Sentencing Commission",
  "U.S. Tax Court",
  "U.S. Trade and Development Agency",
  "U.S. Trustee Program",
  "Udall Foundation",
  "United Nations",
  "Water Resources Council",
  "Western Area Power Administration",
] as const;

export const waepaFederalAgencyOptions: FieldOption[] =
  waepaFederalAgencyLabels.map((label) => ({ value: label, label }));
