export type ComponentRow = {
  name: string;
  category: string;
  description: string;
  sourcePath: string;
  usedIn: string;
  /** Verified Storybook selection ID, including the story suffix. Omitted when no story exists. */
  storybookId?: string;
};

/**
 * Inventory of reusable app-specific UI components. Storybook is the
 * component-library source of truth; this data supports coverage auditing.
 */
export const componentsData: ComponentRow[] = [
  {
    name: "ApplicationDocumentPreview",
    category: "content",
    description:
      "Full review/preview of application data grouped by page sections with edit buttons.",
    sourcePath: "src/components/content/ApplicationDocumentPreview.tsx",
    usedIn: "Review page",
    storybookId: "content-applicationdocumentpreview--default",
  },
  {
    name: "HelpChips",
    category: "content",
    description: "Horizontally scrollable row of clickable help topic chips.",
    sourcePath: "src/components/content/HelpChips.tsx",
    usedIn: "PageHeader help section",
    storybookId: "content-helpchips--default",
  },
  {
    name: "LegalDocList",
    category: "content",
    description: "Renders structured legal documents from content data.",
    sourcePath: "src/components/content/LegalDocList.tsx",
    usedIn: "AppFooter legal modals",
    storybookId: "content-legaldoclist--terms-of-use",
  },
  {
    name: "QuickDecisionExplainer",
    category: "content",
    description:
      "Explainer content for QuickDecision℠ with styled marks and drawer. Documented together with QuickDecisionInfoBox as \"QuickDecision content, two surfaces\" per the Phase 1 audit.",
    sourcePath: "src/components/content/QuickDecisionExplainer.tsx",
    usedIn: "AppMenu (via HowApplyingWorksPanel), QuickDecisionInfoBox",
    storybookId: "content-quickdecision--drawer-explainer-content",
  },
  {
    name: "QuickDecisionInfoBox",
    category: "content",
    description: "Green info panel promoting QuickDecision℠ eligibility.",
    sourcePath: "src/components/content/QuickDecisionInfoBox.tsx",
    usedIn: "ProductCatalog, CoverageOptionsPanel",
    storybookId: "content-quickdecision--info-box-inline-collapse",
  },
  {
    name: "EmptyState",
    category: "feedback",
    description:
      "Icon + title + body placeholder for empty or unavailable content.",
    sourcePath: "src/components/feedback/EmptyState.tsx",
    usedIn: "CoverageCart, QuoteCalculator, error states",
    storybookId: "feedback-emptystate--default",
  },
  {
    name: "LoadingOverlay",
    category: "feedback",
    description: "Multi-size loading spinner with optional status message.",
    sourcePath: "src/components/feedback/LoadingOverlay.tsx",
    usedIn: "Page transitions, async actions",
    storybookId: "feedback-loadingoverlay--small",
  },
  {
    name: "PageAlert",
    category: "feedback",
    description:
      "Full-width contextual alert above form content. PageErrorAlert is a deprecated re-export of this component.",
    sourcePath: "src/components/feedback/PageAlert.tsx",
    usedIn: "PageShell error/info display",
    storybookId: "feedback-pagealert--error",
  },
  {
    name: "PageTransitionSkeleton",
    category: "feedback",
    description: "Skeleton placeholder during page transitions.",
    sourcePath: "src/components/feedback/PageTransitionSkeleton.tsx",
    usedIn: "RoutePage transition state",
    storybookId: "feedback-pagetransitionskeleton--with-message",
  },
  {
    name: "AppSnackbar",
    category: "feedback",
    description:
      "Base snackbar component with severity, message, and responsive positioning (bottom on small screens, top-center on large screens). Used by ProgressSavedSnackbar and the Coverage page Added feedback.",
    sourcePath: "src/components/feedback/AppSnackbar.tsx",
    usedIn: "ProgressSavedSnackbar, Coverage page",
    storybookId: "feedback-appsnackbar--success",
  },
  {
    name: "ProgressSavedSnackbar",
    category: "feedback",
    description:
      "Success snackbar confirming form progress saved. Delegates to AppSnackbar.",
    sourcePath: "src/components/feedback/ProgressSavedSnackbar.tsx",
    usedIn: "RoutePage (global)",
    storybookId: "feedback-appsnackbar--progress-saved-preset",
  },
  {
    name: "ConditionalGroup",
    category: "forms",
    description:
      "Left-bordered indented container for conditional follow-up questions.",
    sourcePath: "src/components/forms/ConditionalGroup.tsx",
    usedIn: "Coverage, Profile, Eligibility pages",
    storybookId: "forms-conditionalgroup--hidden-and-revealed",
  },
  {
    name: "EligibilityFields",
    category: "forms",
    description:
      "Shared eligibility input fields (DOB, gender, tobacco, state, ZIP) used by the Quote Calculator and Home page quote entry.",
    sourcePath: "src/components/forms/EligibilityFields.tsx",
    usedIn: "QuoteCalculator, Home page",
    storybookId: "coverage-commerce-eligibilityfields--default",
  },
  {
    name: "EstimatorProductCard",
    category: "forms",
    description:
      "Simplified member-only product card (no riders/waiting periods) used inside the Quote Calculator estimator.",
    sourcePath: "src/components/forms/EstimatorProductCard.tsx",
    usedIn: "QuoteCalculator",
    storybookId: "coverage-commerce-estimatorproductcard--unselected",
  },
  {
    name: "CoverageCategorySelector",
    category: "forms",
    description: "Multi-select toggle list for choosing coverage categories.",
    sourcePath: "src/components/forms/CoverageCategorySelector.tsx",
    usedIn: "Coverage page, QuoteCalculator",
    storybookId: "coverage-commerce-coveragecategoryselector--default",
  },
  {
    name: "CoverageNeedsCalculator",
    category: "forms",
    description: "Interactive calculator estimating recommended life coverage.",
    sourcePath: "src/components/forms/CoverageNeedsCalculator.tsx",
    usedIn: "AppMenu drawer",
    storybookId: "coverage-commerce-coverageneedscalculator--default",
  },
  {
    name: "CoverageQuestions",
    category: "forms",
    description:
      "Category-level coverage questions (tobacco, income) with section visibility.",
    sourcePath: "src/components/forms/CoverageQuestions.tsx",
    usedIn: "Coverage page",
    storybookId: "coverage-commerce-coveragequestions--life-insurance-selected",
  },
  {
    name: "DynamicList",
    category: "forms",
    description: "Add/edit/remove list with modal-based form for items.",
    sourcePath: "src/components/forms/DynamicList.tsx",
    usedIn: "Beneficiary, Profile, Eligibility pages",
    storybookId: "forms-dynamiclist--empty",
  },
  {
    name: "DynamicListItem",
    category: "forms",
    description: "Single bordered card item in a DynamicList.",
    sourcePath: "src/components/forms/DynamicListItem.tsx",
    usedIn: "DynamicList children",
    storybookId: "forms-dynamiclistitem--default",
  },
  {
    name: "FieldRenderer",
    category: "forms",
    description:
      "Universal form field renderer: text, date, radio, dropdown, checkbox, multi-select, searchable-select.",
    sourcePath: "src/components/forms/FieldRenderer.tsx",
    usedIn: "All form pages (field rendering)",
    storybookId: "forms-fieldrenderer--playground",
  },
  {
    name: "PhysicianInformation",
    category: "forms",
    description: "Physician info section with name/address/phone fields.",
    sourcePath: "src/components/forms/PhysicianInformation.tsx",
    usedIn: "Profile page",
    storybookId: "coverage-commerce-physicianinformation--default",
  },
  {
    name: "ProductCatalog",
    category: "forms",
    description:
      "Full product catalog with applicant checkboxes, amounts, riders, rates.",
    sourcePath: "src/components/forms/ProductCatalog.tsx",
    usedIn: "Coverage page",
    storybookId: "coverage-commerce-productcatalog--interactive",
  },
  {
    name: "QuoteCalculator",
    category: "forms",
    description: "Quote/rate calculator drawer with category selection.",
    sourcePath: "src/components/forms/QuoteCalculator.tsx",
    usedIn: "Home page, Membership page",
    storybookId: "coverage-commerce-quotecalculator--collects-eligibility",
  },
  {
    name: "SelectionGroup",
    category: "forms",
    description:
      "Full-width bordered clickable row for checkbox/radio/icon-toggle options.",
    sourcePath: "src/components/forms/SelectionGroup.tsx",
    usedIn: "FieldRenderer (radio/checkbox)",
    storybookId: "forms-selectiongroup--checkbox-row-unselected",
  },
  {
    name: "AppBody",
    category: "layout",
    description: "Main content area wrapper with scroll-to-top on navigation.",
    sourcePath: "src/components/layout/AppBody.tsx",
    usedIn: "AppShell",
    storybookId: "layout-appbody--default",
  },
  {
    name: "AppDrawer",
    category: "layout",
    description: "Slide-in drawer (swipeable on mobile) with title and close.",
    sourcePath: "src/components/layout/AppDrawer.tsx",
    usedIn: "CoverageCart, AppMenu",
    storybookId: "overlays-appdrawer--default",
  },
  {
    name: "AppFooter",
    category: "layout",
    description: "Footer with client support info and legal doc modals.",
    sourcePath: "src/components/layout/AppFooter.tsx",
    usedIn: "AppShell",
    storybookId: "layout-appfooter--default",
  },
  {
    name: "AppHeader",
    category: "layout",
    description:
      "Top app bar with logo, menu, cart badge, progress bar, save/help. Determines its current page via window.location.pathname through its own history-patched subscription, not react-router's useLocation().",
    sourcePath: "src/components/layout/AppHeader.tsx",
    usedIn: "AppShell",
    storybookId: "layout-appheader--application-form-variant",
  },
  {
    name: "AppMenu",
    category: "layout",
    description:
      "Full-screen side drawer with coverage options, calculator, support. Uses HowApplyingWorksPanel and CoverageOptionsPanel internally for the coverage-options and how-applying-works sub-drawers.",
    sourcePath: "src/components/layout/AppMenu.tsx",
    usedIn: "AppHeader hamburger menu",
    storybookId: "layout-appmenu--default",
  },
  {
    name: "AppModal",
    category: "layout",
    description: "Reusable responsive dialog/modal with title, close, actions.",
    sourcePath: "src/components/layout/AppModal.tsx",
    usedIn: "ConfirmationDialog, SendApplicationDialog, AppFooter legal modals, CoverageCart, DynamicList",
    storybookId: "overlays-appmodal--default",
  },
  {
    name: "AppShell",
    category: "layout",
    description: "Top-level layout shell selecting chrome variant.",
    sourcePath: "src/components/layout/AppShell.tsx",
    usedIn: "Router (wraps all pages)",
    storybookId: "layout-appshell--application-form-variant",
  },
  {
    name: "ApplicantSectionDivider",
    category: "layout",
    description: "Section header with icon/label for applicant sections.",
    sourcePath: "src/components/layout/ApplicantSectionDivider.tsx",
    usedIn: "Coverage, Profile pages",
    storybookId: "layout-applicantsectiondivider--member-section",
  },
  {
    name: "CategoryCard",
    category: "layout",
    description: "Surface card wrapping a category header + content stack.",
    sourcePath: "src/components/layout/CategoryCard.tsx",
    usedIn: "ProductCatalog",
    storybookId: "layout-categorycard--default",
  },
  {
    name: "CategoryHeader",
    category: "layout",
    description: "h6 heading with optional icon for coverage category.",
    sourcePath: "src/components/layout/CategoryHeader.tsx",
    usedIn: "CategoryCard",
    storybookId: "layout-categoryheader--with-icon",
  },
  {
    name: "ClientHelpBanner",
    category: "layout",
    description: "Support banner with phone, chat, and schedule actions.",
    sourcePath: "src/components/layout/ClientHelpBanner.tsx",
    usedIn: "AppHeader (renders when the active client has a support phone)",
    storybookId: "layout-clienthelpbanner--default",
  },
  {
    name: "ConfirmationDialog",
    category: "layout",
    description: "Yes/Cancel confirmation modal built on AppModal.",
    sourcePath: "src/components/layout/ConfirmationDialog.tsx",
    usedIn: "Review, Coverage",
    storybookId: "overlays-confirmationdialog--default",
  },
  {
    name: "CookieDialog",
    category: "layout",
    description:
      "Fixed-position cookie consent banner — not a true Dialog (no backdrop/focus-trap) despite the name.",
    sourcePath: "src/components/layout/CookieDialog.tsx",
    usedIn: "AppShell (global)",
    storybookId: "overlays-cookiedialog--default",
  },
  {
    name: "SendApplicationDialog",
    category: "layout",
    description:
      "Yes/Cancel confirmation modal (built on AppModal) shown before sending an application to a recipient by email.",
    sourcePath: "src/components/layout/SendApplicationDialog.tsx",
    usedIn: "Profile, Review (advisor ↔ applicant handoff)",
    storybookId: "overlays-sendapplicationdialog--default",
  },
  {
    name: "FormShell",
    category: "layout",
    description: "Rounded elevated Paper container wrapping form content.",
    sourcePath: "src/components/layout/FormShell.tsx",
    usedIn: "All form pages",
    storybookId: "layout-formshell--default",
  },
  {
    name: "PageHeader",
    category: "layout",
    description: "Page title + subtitle + optional help.",
    sourcePath: "src/components/layout/PageHeader.tsx",
    usedIn: "All form pages",
    storybookId: "layout-pageheader--default",
  },
  {
    name: "PageShell",
    category: "layout",
    description: "Full page layout with title, error display, max-width.",
    sourcePath: "src/components/layout/PageShell.tsx",
    usedIn: "All page wrappers",
    storybookId: "layout-pageshell--default",
  },
  {
    name: "PageTitle",
    category: "layout",
    description: "Page title Typography with optional back arrow.",
    sourcePath: "src/components/layout/PageTitle.tsx",
    usedIn: "Non-form pages",
    storybookId: "layout-pagetitle--title-only",
  },
  {
    name: "ProductCard",
    category: "layout",
    description: "Bordered card for products with selected/unselected states.",
    sourcePath: "src/components/layout/ProductCard.tsx",
    usedIn: "ProductCatalog, QuoteEstimator",
    storybookId: "layout-productcard--unselected",
  },
  {
    name: "QuoteModal",
    category: "layout",
    description:
      "Quote/rate comparison modal containing EstimatorProductCard entries per product. Confirmed dead code as of the 2026-09 Storybook audit — a repo-wide grep found zero render sites outside a documentation demo, and it appears to duplicate QuoteCalculator. Kept in the repo but intentionally not given a Storybook story.",
    sourcePath: "src/components/layout/QuoteModal.tsx",
    usedIn: "Not rendered anywhere (dead code — previously claimed \"Coverage page, AppHeader\", unconfirmed by grep)",
  },
  {
    name: "SectionDivider",
    category: "layout",
    description: "Chip-based or text section header divider.",
    sourcePath: "src/components/layout/SectionDivider.tsx",
    usedIn: "Form pages (visual separators)",
    storybookId: "layout-sectiondivider--subsection-preset",
  },
  {
    name: "PageNav",
    category: "navigation",
    description: "Bottom-of-page Next button with loading spinner.",
    sourcePath: "src/components/navigation/PageNav.tsx",
    usedIn: "All form pages",
    storybookId: "navigation-pagenav--default",
  },
  {
    name: "ProgressStep",
    category: "navigation",
    description: "Breadcrumb/stepper progress indicator.",
    sourcePath: "src/components/navigation/ProgressStep.tsx",
    usedIn: "AppHeader progress bar",
    storybookId: "navigation-progressstep--collapsed-steps",
  },
  {
    name: "FeaturedBadge",
    category: "ui",
    description: "Small Featured chip badge with star icon.",
    sourcePath: "src/components/ui/FeaturedBadge.tsx",
    usedIn: "ProductCard (featured)",
    storybookId: "coverage-commerce-product-adornments--side-by-side",
  },
  {
    name: "ProductCostBreakdown",
    category: "ui",
    description: "Itemized premium + rider + policy fee breakdown.",
    sourcePath: "src/components/ui/ProductCostBreakdown.tsx",
    usedIn: "ProductCatalog (client-config gated)",
    storybookId: "coverage-commerce-productcostbreakdown--monthly",
  },
  {
    name: "QuickDecisionIndicator",
    category: "ui",
    description: "Green lightning bolt icon for QuickDecision℠.",
    sourcePath: "src/components/ui/QuickDecisionIndicator.tsx",
    usedIn: "ProductCard, ProductCatalog",
    storybookId: "coverage-commerce-product-adornments--side-by-side",
  },
  {
    name: "RateFrequencyToggle",
    category: "ui",
    description: "Switch toggle for monthly/annual rate display.",
    sourcePath: "src/components/ui/RateFrequencyToggle.tsx",
    usedIn: "CoverageCart, QuoteCalculator",
    storybookId: "coverage-commerce-ratefrequencytoggle--unchecked",
  },
  {
    name: "CoverageCart",
    category: "ui",
    description:
      "Selected coverage summary with drawer and inline variants. Renders per-product cost breakdown and total. Replaces the former CartDrawer + TotalCostCart split.",
    sourcePath: "src/components/ui/CoverageCart.tsx",
    usedIn: "AppHeader (drawer), ProductCatalog (inline)",
    storybookId: "coverage-commerce-coveragecart--populated-drawer",
  },
  {
    name: "TotalCostSummary",
    category: "ui",
    description: "Total Estimated Cost summary panel.",
    sourcePath: "src/components/ui/TotalCostSummary.tsx",
    usedIn: "CoverageCart, QuoteCalculator",
    storybookId: "coverage-commerce-totalcostsummary--default",
  },
  {
    name: "HowApplyingWorksPanel",
    category: "ui",
    description:
      "Renders the How Applying Works step list in either 'page' or 'drawer' variant. " +
      "In drawer variant manages its own sub-drawers for Application Review and QuickDecision℠ content.",
    sourcePath: "src/components/ui/HowApplyingWorksPanel.tsx",
    usedIn: "Home page, AppMenu drawer",
    storybookId: "coverage-commerce-howapplyingworkspanel--page-variant",
  },
  {
    name: "CoverageOptionsPanel",
    category: "ui",
    description:
      "Tabbed coverage category browser showing products, amounts, eligible applicants, " +
      "and QD indicator. Supports 'page' and 'drawer' variants. Featured products sort first. " +
      "Product names were fixed from placeholder href=\"#\" links to plain text in the 2026-09 Storybook pass, since no real product-detail destination exists.",
    sourcePath: "src/components/ui/CoverageOptionsPanel.tsx",
    usedIn: "Home page, AppMenu drawer",
    storybookId: "coverage-commerce-coverageoptionspanel--page-variant",
  },
  {
    name: "CoveragePortfolioDrawer",
    category: "ui",
    description:
      "Read-only existing-coverage drawer shown to TPA-verified members on the Coverage page. Uses hardcoded dummy portfolio data, not real member records.",
    sourcePath: "src/components/ui/CoveragePortfolioDrawer.tsx",
    usedIn: "Coverage page (TPA-verified users only)",
    storybookId: "coverage-commerce-coverageportfoliodrawer--member-only",
  },
  {
    name: "MemberVerification",
    category: "ui",
    description:
      "Multi-step identity-verification modal with dummy LexisNexis-style security questions (no real identity-verification integration).",
    sourcePath: "src/components/ui/MemberVerification.tsx",
    usedIn: "Eligibility page",
    storybookId: "coverage-commerce-memberverification--interactive",
  },
  {
    name: "RateFrequencyControl",
    category: "ui",
    description: "Canonical labeled Monthly/Annual rate-frequency control.",
    sourcePath: "src/components/ui/RateFrequencyControl.tsx",
    usedIn: "CoverageCart, QuoteCalculator",
    storybookId: "coverage-commerce-ratefrequencycontrol--interactive",
  },
  {
    name: "ExpiringCodeAlert",
    category: "feedback",
    description: "Active, resent, and expired alerts for resume links and verification codes.",
    sourcePath: "src/components/feedback/ExpiringCodeAlert.tsx",
    usedIn: "Resume, ResumeCode",
    storybookId: "feedback-resume-expiration--active-link",
  },
  {
    name: "ResendCountdownRow",
    category: "feedback",
    description: "Countdown label and resend action paired with useCountdown.",
    sourcePath: "src/components/feedback/ResendCountdownRow.tsx",
    usedIn: "Resume, ResumeCode",
    storybookId: "feedback-resume-expiration--active-link",
  },
  {
    name: "ProcessingStatusPage",
    category: "feedback",
    description: "Centered spinner, mark, heading, and body for external processing states.",
    sourcePath: "src/components/feedback/ProcessingStatusPage.tsx",
    usedIn: "DocuSign, HealthQd",
    storybookId: "feedback-processingstatuspage--external-service",
  },
  {
    name: "FieldGrid",
    category: "layout",
    description: "Responsive equal, wide/narrow, and wide/two-narrow form rows.",
    sourcePath: "src/components/layout/FieldGrid.tsx",
    usedIn: "Membership, Eligibility, Beneficiary, Contact, Profile",
    storybookId: "layout-fieldgrid--equal-columns",
  },
  {
    name: "DetailsTable",
    category: "layout",
    description: "Accessible label/value confirmation table.",
    sourcePath: "src/components/layout/DetailsTable.tsx",
    usedIn: "AdvisorSendConfirmation, ApplicationEditConfirmation",
    storybookId: "application-patterns-detailstable--confirmation-details",
  },
  {
    name: "IconListItem",
    category: "layout",
    description: "Two-column list row with a leading icon or ordinal and content.",
    sourcePath: "src/components/layout/IconListItem.tsx",
    usedIn: "YesNoDetailList",
    storybookId: "application-patterns-yesnodetaillist--interactive",
  },
  {
    name: "RadioSelectionGroup",
    category: "forms",
    description: "Accessible radio group rendered with canonical SelectionGroup rows.",
    sourcePath: "src/components/forms/RadioSelectionGroup.tsx",
    usedIn: "Beneficiary, ResumeMethod",
    storybookId: "forms-radioselectiongroup--interactive",
  },
  {
    name: "YesNoDetailList",
    category: "forms",
    description: "Numbered yes/no questions that reveal DynamicList details on Yes.",
    sourcePath: "src/components/forms/YesNoDetailList.tsx",
    usedIn: "HealthSi, HealthLi, HealthDi",
    storybookId: "application-patterns-yesnodetaillist--interactive",
  },
];
